const express=require('express');
const path=require('path');
const cors=require('cors');
const app=express();
app.use(express.static(path.join(__dirname,'public')));
app.use(cors());
app.use(express.json());
let users=[],deposits=[];
app.get('/',(req,res)=>res.send('live'));
app.post('/api/signup',(req,res)=>{const{email,password}=req.body;if(users.find(u=>u.email===email))return res.json({success:false});users.push({email,password,balance:0});res.json({success:true});});
app.post('/api/login',(req,res)=>{const{email,password}=req.body;let u=users.find(x=>x.email===email&&x.password===password);if(!u){u={email,password,balance:0};users.push(u);}res.json({success:true,email:u.email,balance:u.balance});});
app.post('/api/balance',(req,res)=>{const u=users.find(x=>x.email===req.body.email);res.json({balance:u?u.balance:0});});
app.post('/api/my-deposits',(req,res)=>{const list=deposits.filter(d=>d.email===req.body.email).reverse();res.json({deposits:list});});
app.post('/api/deposit',(req,res)=>{const{email,amount,txHash,hash,txId}=req.body;const finalHash=txHash||hash||txId||'No TX';deposits.push({id:Date.now().toString(),email,amount:Number(amount),txHash:finalHash,status:'pending',createdAt:new Date()});res.json({success:true});});
app.get('/api/admin/deposits',(req,res)=>res.json({deposits:deposits.slice().reverse()}));
app.post('/api/admin/approve',(req,res)=>{const dep=deposits.find(d=>d.id===req.body.id);if(!dep)return res.json({success:false});dep.status='approved';let u=users.find(x=>x.email===dep.email);if(!u){u={email:dep.email,password:'x',balance:0};users.push(u);}u.balance+=Number(dep.amount);res.json({success:true});});
app.listen(process.env.PORT||10000,()=>console.log("Running"));
